[webservers]
server-001 ansible_host=localhost ansible_connection=local
server-002 ansible_host=localhost ansible_connection=local
server-003 ansible_host=localhost ansible_connection=local

[webservers:vars]
ansible_user=runner